services:
  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
