services:
  backend-green:
    extends:
      file: docker-compose.yml
      service: backend
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_NAME=${MYSQL_NAME}
      - ELASTIC_NODE=${ELASTIC_NODE}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_TTL=${REDIS_TTL}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - LOG_LEVEL=${LOG_LEVEL}
    networks:
      - app-network
      - proxy-network

  frontend-green:
    extends:
      file: docker-compose.yml
      service: frontend
    environment:
      - BACKEND_URL=http://backend-green:3000
    networks:
      - app-network
      - proxy-network
    extra_hosts:
      - "db-host:${DATABASE_HOST}"
networks:
  proxy-network:
    external: true
