services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dev_db
      MYSQL_USER: honey
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql_data
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: --bind-address=0.0.0.0
  backend:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
      - "9001:9001"
    environment:
      NODE_ENV: development
      MYSQL_HOST: mysql-container
      MYSQL_PORT: 3306
      MYSQL_USERNAME: honey
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: dev_db
      MYSQL_NAME: dev_db

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
volumes:
  mysql_data:
