name: 백엔드 배포
on:
  push:
    branches: [main]
    paths:
      - "packages/backend/**"
      - "packages/shared/**"
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v2

      - name: NCP 컨테이너 레지스트리 로그인
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: 도커 이미지 빌드 및 푸시
        id: docker-build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./packages/backend/Dockerfile.blue
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY_URL }}/backend:latest


  pull_from_registry:
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: SSH로 서버 접속
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}

      - name: NCP 컨테이너 레지스트리 로그인
        run: |
          docker login -u ${{ secrets.NCP_ACCESS_KEY }} -p ${{ secrets.NCP_SECRET_KEY }} ${{ secrets.CONTAINER_REGISTRY_URL }}

      - name: 컨테이너 업데이트
        run: |
            docker stop backend
            docker rm backend
            docker pull ${{ secrets.CONTAINER_REGISTRY_URL }}/backend:latest
            docker run -d --name backend_blue --network product_network -p 3000:3000 ${{ secrets.CONTAINER_REGISTRY_URL }}/backend:latest
