name: 백엔드 배포
on:
  push:
    branches: [main]
    paths:
      - "packages/backend/**"
      - "packages/shared/**"
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v2

      - name: NCP 컨테이너 레지스트리 로그인
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: 도커 이미지 빌드 및 푸시 (Blue)
        id: docker-build-blue
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./packages/backend/Dockerfile.blue
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY_URL }}/backend:blue-latest

      - name: 도커 이미지 빌드 및 푸시 (Green)
        id: docker-build-green
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./packages/backend/Dockerfile.green
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY_URL }}/backend:green-latest

  pull_from_registry:
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: SSH로 서버 접속
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}

      - name: NCP 컨테이너 레지스트리 로그인
        run: |
          docker login -u ${{ secrets.NCP_ACCESS_KEY }} -p ${{ secrets.NCP_SECRET_KEY }} ${{ secrets.CONTAINER_REGISTRY_URL }}

      - name: 현재 실행 중인 Blue/Green 확인
        id: check-current
        run: |
          if docker ps --filter "name=backend_green" --format '{{.Names}}' | grep -w backend_green; then
           echo "current=green" | tee -a $GITHUB_ENV
          else
           echo "current=blue" | tee -a $GITHUB_ENV
          fi

      - name: 컨테이너 업데이트 및 Blue/Green 전환
        run: |
          if [ "$current" = "green" ]; then
            docker stop backend_green || true
            docker rm backend_green || true
            docker pull ${{ secrets.CONTAINER_REGISTRY_URL }}/backend:blue-latest
            docker run -d --name backend_blue --network product_network -p 3000:3000 ${{ secrets.CONTAINER_REGISTRY_URL }}/backend:blue-latest
          else
            docker stop backend_blue || true
            docker rm backend_blue || true
            docker pull ${{ secrets.CONTAINER_REGISTRY_URL }}/backend:green-latest
            docker run -d --name backend_blue --network product_network -p 3001:3000 ${{ secrets.CONTAINER_REGISTRY_URL }}/backend:blue-latest
          fi
